// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio7_BBDD.Entities
{
    public partial class Cliente
    {
        public Cliente()
        {
            TrabajadorCliente = new HashSet<TrabajadorCliente>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        public int? Saldo { get; set; }

        [InverseProperty("Cliente")]
        public virtual ICollection<TrabajadorCliente> TrabajadorCliente { get; set; }
    }
}