// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio7_BBDD.Entities
{
    public partial class TrabajadorCliente
    {
        [Key]
        public Guid Id { get; set; }
        public Guid? TrabajadorId { get; set; }
        public Guid? ClienteId { get; set; }

        [ForeignKey("ClienteId")]
        [InverseProperty("TrabajadorCliente")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey("TrabajadorId")]
        [InverseProperty("TrabajadorCliente")]
        public virtual Trabajador Trabajador { get; set; }
    }
}