// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ejercicios.BBDD.Ejercicios_Con_Relaciones.Entidades
{
    public partial class Empresa
    {
        public Empresa()
        {
            Empleado = new HashSet<Empleado>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        [StringLength(50)]
        public string Localizacion { get; set; }
        [StringLength(50)]
        public string CantidadEmpleados { get; set; }
        [StringLength(50)]
        public string CantidadOficinas { get; set; }

        [InverseProperty("Empresa")]
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}