// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ejercicios.BBDD.Ejercicios_Con_Relaciones.Ejercicio6_BBDD.Entidades
{
    public partial class Empleado
    {
        [Key]
        public Guid Id { get; set; }
        public Guid PersonId { get; set; }
        public Guid EmpresaId { get; set; }
        [StringLength(50)]
        public string Puesto { get; set; }
        public TimeSpan? HoraEntrada { get; set; }
        public TimeSpan? HoraSalida { get; set; }
        public int? PrecioPorHora { get; set; }

        [ForeignKey("EmpresaId")]
        [InverseProperty("Empleado")]
        public virtual Empresa Empresa { get; set; }
        [ForeignKey("PersonId")]
        [InverseProperty("Empleado")]
        public virtual Person Person { get; set; }
    }
}