// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.PruebaBBDD.Entities
{
    public partial class Persona
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        [Column("Surname_1")]
        public string Surname1 { get; set; }
        [Column("Surname_2")]
        public string Surname2 { get; set; }
        public int? Age { get; set; }
    }
}