// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ejercicios.BBDD.Ejercicios_Con_Relaciones.Ejercicio6_BBDD.Entidades
{
    public partial class Client
    {
        [Key]
        public Guid Id { get; set; }
        public Guid PersonId { get; set; }
        public int? Saldo { get; set; }
        public int? HoraServicio { get; set; }

        [ForeignKey("PersonId")]
        [InverseProperty("Client")]
        public virtual Person Person { get; set; }
    }
}