// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio8_BBDD.Data.Entities
{
    public partial class Cliente
    {
        public Cliente()
        {
            Reserva = new HashSet<Reserva>();
        }

        [Key]
        [Column("idCliente")]
        public Guid IdCliente { get; set; }
        [Required]
        [Column("nombre")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nombre { get; set; }
        [Required]
        [Column("apellido")]
        [StringLength(50)]
        [Unicode(false)]
        public string Apellido { get; set; }
        [Required]
        [Column("telefono")]
        [StringLength(20)]
        [Unicode(false)]
        public string Telefono { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}