// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio8_BBDD.Data.Entities
{
    public partial class Habitacion
    {
        public Habitacion()
        {
            Reserva = new HashSet<Reserva>();
        }

        [Key]
        [Column("idHabitacion")]
        public Guid IdHabitacion { get; set; }
        [Column("idHotel")]
        public Guid IdHotel { get; set; }
        [Required]
        [Column("tipo")]
        [StringLength(50)]
        [Unicode(false)]
        public string Tipo { get; set; }
        [Column("precio")]
        public double Precio { get; set; }

        [ForeignKey("IdHotel")]
        [InverseProperty("Habitacion")]
        public virtual Hotel IdHotelNavigation { get; set; }
        [InverseProperty("IdHabitacionNavigation")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}