// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio8_BBDD.Data.Entities
{
    public partial class Reserva
    {
        [Key]
        [Column("idReserva")]
        public Guid IdReserva { get; set; }
        [Column("idHabitacion")]
        public Guid IdHabitacion { get; set; }
        [Column("idCliente")]
        public Guid IdCliente { get; set; }
        [Column("fechaInicio", TypeName = "date")]
        public DateTime FechaInicio { get; set; }
        [Column("fechaFin", TypeName = "date")]
        public DateTime FechaFin { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("Reserva")]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey("IdHabitacion")]
        [InverseProperty("Reserva")]
        public virtual Habitacion IdHabitacionNavigation { get; set; }
    }
}