// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ejercicios.BBDD.Ejercicios_Con_Relaciones.Ejercicio3_BBDD.Entidades
{
    public partial class BankAccount
    {
        [Key]
        public int Id { get; set; }
        public int? Saldo { get; set; }
        public int? Ingreso { get; set; }
        public int? Retirada { get; set; }
        public int? ClientId { get; set; }

        [ForeignKey("ClientId")]
        [InverseProperty("BankAccount")]
        public virtual Cliente Client { get; set; }
    }
}