// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio7_BBDD.Entities
{
    public partial class Cliente
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string NombreCliente { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? FacturaTotal { get; set; }
    }
}