// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio7_BBDD.Entities
{
    public partial class Sucursal
    {
        public Sucursal()
        {
            Trabajador = new HashSet<Trabajador>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string NombreSucursal { get; set; }
        public Guid? CentroId { get; set; }

        [ForeignKey("CentroId")]
        [InverseProperty("Sucursal")]
        public virtual CentroBelleza Centro { get; set; }
        [InverseProperty("Sucursal")]
        public virtual ICollection<Trabajador> Trabajador { get; set; }
    }
}