// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio7_BBDD.Entities
{
    public partial class Trabajador
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string NombreTrabajador { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string PuestoTrabajo { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? CosteDelServicio { get; set; }
        public Guid? SucursalId { get; set; }

        [ForeignKey("SucursalId")]
        [InverseProperty("Trabajador")]
        public virtual Sucursal Sucursal { get; set; }
    }
}