// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio5_BBDD.Entities
{
    public partial class Alumno
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaNacimiento { get; set; }
        public Guid? CentroId { get; set; }

        [ForeignKey("CentroId")]
        [InverseProperty("Alumno")]
        public virtual Centro Centro { get; set; }
    }
}