// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio5_BBDD.Entities
{
    public partial class Asignatura
    {
        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        public Guid? CursoId { get; set; }
        public Guid? ProfesorId { get; set; }

        [ForeignKey("CursoId")]
        [InverseProperty("Asignatura")]
        public virtual Curso Curso { get; set; }
        [ForeignKey("ProfesorId")]
        [InverseProperty("Asignatura")]
        public virtual Profesor Profesor { get; set; }
    }
}