// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio5_BBDD.Entities
{
    public partial class Centro
    {
        public Centro()
        {
            Alumno = new HashSet<Alumno>();
            Curso = new HashSet<Curso>();
            Profesor = new HashSet<Profesor>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        [Column("CP")]
        [StringLength(50)]
        public string Cp { get; set; }

        [InverseProperty("Centro")]
        public virtual ICollection<Alumno> Alumno { get; set; }
        [InverseProperty("Centro")]
        public virtual ICollection<Curso> Curso { get; set; }
        [InverseProperty("Centro")]
        public virtual ICollection<Profesor> Profesor { get; set; }
    }
}