// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BBDD.Ejercicios.Ejercicios_Con_Relaciones.Ejercicio5_BBDD.Entities
{
    public partial class Profesor
    {
        public Profesor()
        {
            Asignatura = new HashSet<Asignatura>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        public int? Telefono { get; set; }
        public Guid? CentroId { get; set; }

        [ForeignKey("CentroId")]
        [InverseProperty("Profesor")]
        public virtual Centro Centro { get; set; }
        [InverseProperty("Profesor")]
        public virtual ICollection<Asignatura> Asignatura { get; set; }
    }
}